name = "BLAKJac"
uuid = "71791924-b903-4d6d-b97e-d26ae20ee392"
authors = ["m.fuderer@umcutrecht.nl"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
